# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from api.ec_group_messages_pb2 import (
    HexPointBaseGroup1Affine as api___ec_group_messages_pb2___HexPointBaseGroup1Affine,
    HexPointBaseGroup2Affine as api___ec_group_messages_pb2___HexPointBaseGroup2Affine,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class VerificationKeyGROTH16(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    abc_g1 = ... # type: typing___Text

    @property
    def alpha_g1(self) -> api___ec_group_messages_pb2___HexPointBaseGroup1Affine: ...

    @property
    def beta_g2(self) -> api___ec_group_messages_pb2___HexPointBaseGroup2Affine: ...

    @property
    def delta_g2(self) -> api___ec_group_messages_pb2___HexPointBaseGroup2Affine: ...

    def __init__(self,
        *,
        alpha_g1 : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup1Affine] = None,
        beta_g2 : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup2Affine] = None,
        delta_g2 : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup2Affine] = None,
        abc_g1 : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> VerificationKeyGROTH16: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"alpha_g1",u"beta_g2",u"delta_g2"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"abc_g1",u"alpha_g1",u"beta_g2",u"delta_g2"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"alpha_g1",b"alpha_g1",u"beta_g2",b"beta_g2",u"delta_g2",b"delta_g2"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"abc_g1",b"abc_g1",u"alpha_g1",b"alpha_g1",u"beta_g2",b"beta_g2",u"delta_g2",b"delta_g2"]) -> None: ...

class ExtendedProofGROTH16(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    inputs = ... # type: typing___Text

    @property
    def a(self) -> api___ec_group_messages_pb2___HexPointBaseGroup1Affine: ...

    @property
    def b(self) -> api___ec_group_messages_pb2___HexPointBaseGroup2Affine: ...

    @property
    def c(self) -> api___ec_group_messages_pb2___HexPointBaseGroup1Affine: ...

    def __init__(self,
        *,
        a : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup1Affine] = None,
        b : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup2Affine] = None,
        c : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup1Affine] = None,
        inputs : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> ExtendedProofGROTH16: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"a",u"b",u"c"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"a",u"b",u"c",u"inputs"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"a",b"a",u"b",b"b",u"c",b"c"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"a",b"a",u"b",b"b",u"c",b"c",u"inputs",b"inputs"]) -> None: ...
