# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/pghr13_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api import ec_group_messages_pb2 as api_dot_ec__group__messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/pghr13_messages.proto',
  package='zeth_proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19\x61pi/pghr13_messages.proto\x12\nzeth_proto\x1a\x1b\x61pi/ec_group_messages.proto\"\x96\x03\n\x15VerificationKeyPGHR13\x12/\n\x01\x61\x18\x01 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup2Affine\x12/\n\x01\x62\x18\x02 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup1Affine\x12/\n\x01\x63\x18\x03 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup2Affine\x12\x33\n\x05gamma\x18\x04 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup2Affine\x12;\n\rgamma_beta_g1\x18\x05 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup1Affine\x12;\n\rgamma_beta_g2\x18\x06 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup2Affine\x12/\n\x01z\x18\x07 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup2Affine\x12\n\n\x02ic\x18\x08 \x01(\t\"\xb3\x03\n\x13\x45xtendedProofPGHR13\x12/\n\x01\x61\x18\x01 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup1Affine\x12\x31\n\x03\x61_p\x18\x02 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup1Affine\x12/\n\x01\x62\x18\x03 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup2Affine\x12\x31\n\x03\x62_p\x18\x04 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup1Affine\x12/\n\x01\x63\x18\x05 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup1Affine\x12\x31\n\x03\x63_p\x18\x06 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup1Affine\x12/\n\x01h\x18\x07 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup1Affine\x12/\n\x01k\x18\x08 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup1Affine\x12\x0e\n\x06inputs\x18\t \x01(\tb\x06proto3')
  ,
  dependencies=[api_dot_ec__group__messages__pb2.DESCRIPTOR,])




_VERIFICATIONKEYPGHR13 = _descriptor.Descriptor(
  name='VerificationKeyPGHR13',
  full_name='zeth_proto.VerificationKeyPGHR13',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='zeth_proto.VerificationKeyPGHR13.a', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='zeth_proto.VerificationKeyPGHR13.b', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c', full_name='zeth_proto.VerificationKeyPGHR13.c', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gamma', full_name='zeth_proto.VerificationKeyPGHR13.gamma', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gamma_beta_g1', full_name='zeth_proto.VerificationKeyPGHR13.gamma_beta_g1', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gamma_beta_g2', full_name='zeth_proto.VerificationKeyPGHR13.gamma_beta_g2', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='zeth_proto.VerificationKeyPGHR13.z', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ic', full_name='zeth_proto.VerificationKeyPGHR13.ic', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=477,
)


_EXTENDEDPROOFPGHR13 = _descriptor.Descriptor(
  name='ExtendedProofPGHR13',
  full_name='zeth_proto.ExtendedProofPGHR13',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='zeth_proto.ExtendedProofPGHR13.a', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='a_p', full_name='zeth_proto.ExtendedProofPGHR13.a_p', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='zeth_proto.ExtendedProofPGHR13.b', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b_p', full_name='zeth_proto.ExtendedProofPGHR13.b_p', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c', full_name='zeth_proto.ExtendedProofPGHR13.c', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c_p', full_name='zeth_proto.ExtendedProofPGHR13.c_p', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='zeth_proto.ExtendedProofPGHR13.h', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='k', full_name='zeth_proto.ExtendedProofPGHR13.k', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='zeth_proto.ExtendedProofPGHR13.inputs', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=915,
)

_VERIFICATIONKEYPGHR13.fields_by_name['a'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP2AFFINE
_VERIFICATIONKEYPGHR13.fields_by_name['b'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP1AFFINE
_VERIFICATIONKEYPGHR13.fields_by_name['c'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP2AFFINE
_VERIFICATIONKEYPGHR13.fields_by_name['gamma'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP2AFFINE
_VERIFICATIONKEYPGHR13.fields_by_name['gamma_beta_g1'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP1AFFINE
_VERIFICATIONKEYPGHR13.fields_by_name['gamma_beta_g2'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP2AFFINE
_VERIFICATIONKEYPGHR13.fields_by_name['z'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP2AFFINE
_EXTENDEDPROOFPGHR13.fields_by_name['a'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP1AFFINE
_EXTENDEDPROOFPGHR13.fields_by_name['a_p'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP1AFFINE
_EXTENDEDPROOFPGHR13.fields_by_name['b'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP2AFFINE
_EXTENDEDPROOFPGHR13.fields_by_name['b_p'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP1AFFINE
_EXTENDEDPROOFPGHR13.fields_by_name['c'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP1AFFINE
_EXTENDEDPROOFPGHR13.fields_by_name['c_p'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP1AFFINE
_EXTENDEDPROOFPGHR13.fields_by_name['h'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP1AFFINE
_EXTENDEDPROOFPGHR13.fields_by_name['k'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP1AFFINE
DESCRIPTOR.message_types_by_name['VerificationKeyPGHR13'] = _VERIFICATIONKEYPGHR13
DESCRIPTOR.message_types_by_name['ExtendedProofPGHR13'] = _EXTENDEDPROOFPGHR13
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VerificationKeyPGHR13 = _reflection.GeneratedProtocolMessageType('VerificationKeyPGHR13', (_message.Message,), {
  'DESCRIPTOR' : _VERIFICATIONKEYPGHR13,
  '__module__' : 'api.pghr13_messages_pb2'
  # @@protoc_insertion_point(class_scope:zeth_proto.VerificationKeyPGHR13)
  })
_sym_db.RegisterMessage(VerificationKeyPGHR13)

ExtendedProofPGHR13 = _reflection.GeneratedProtocolMessageType('ExtendedProofPGHR13', (_message.Message,), {
  'DESCRIPTOR' : _EXTENDEDPROOFPGHR13,
  '__module__' : 'api.pghr13_messages_pb2'
  # @@protoc_insertion_point(class_scope:zeth_proto.ExtendedProofPGHR13)
  })
_sym_db.RegisterMessage(ExtendedProofPGHR13)


# @@protoc_insertion_point(module_scope)
