# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/snark_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api import pghr13_messages_pb2 as api_dot_pghr13__messages__pb2
from api import groth16_messages_pb2 as api_dot_groth16__messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/snark_messages.proto',
  package='zeth_proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18\x61pi/snark_messages.proto\x12\nzeth_proto\x1a\x19\x61pi/pghr13_messages.proto\x1a\x1a\x61pi/groth16_messages.proto\"\xa5\x01\n\x0fVerificationKey\x12\x44\n\x17pghr13_verification_key\x18\x01 \x01(\x0b\x32!.zeth_proto.VerificationKeyPGHR13H\x00\x12\x46\n\x18groth16_verification_key\x18\x02 \x01(\x0b\x32\".zeth_proto.VerificationKeyGROTH16H\x00\x42\x04\n\x02VK\"\x9b\x01\n\rExtendedProof\x12@\n\x15pghr13_extended_proof\x18\x01 \x01(\x0b\x32\x1f.zeth_proto.ExtendedProofPGHR13H\x00\x12\x42\n\x16groth16_extended_proof\x18\x02 \x01(\x0b\x32 .zeth_proto.ExtendedProofGROTH16H\x00\x42\x04\n\x02\x45Pb\x06proto3')
  ,
  dependencies=[api_dot_pghr13__messages__pb2.DESCRIPTOR,api_dot_groth16__messages__pb2.DESCRIPTOR,])




_VERIFICATIONKEY = _descriptor.Descriptor(
  name='VerificationKey',
  full_name='zeth_proto.VerificationKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pghr13_verification_key', full_name='zeth_proto.VerificationKey.pghr13_verification_key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='groth16_verification_key', full_name='zeth_proto.VerificationKey.groth16_verification_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='VK', full_name='zeth_proto.VerificationKey.VK',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=96,
  serialized_end=261,
)


_EXTENDEDPROOF = _descriptor.Descriptor(
  name='ExtendedProof',
  full_name='zeth_proto.ExtendedProof',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pghr13_extended_proof', full_name='zeth_proto.ExtendedProof.pghr13_extended_proof', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='groth16_extended_proof', full_name='zeth_proto.ExtendedProof.groth16_extended_proof', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='EP', full_name='zeth_proto.ExtendedProof.EP',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=264,
  serialized_end=419,
)

_VERIFICATIONKEY.fields_by_name['pghr13_verification_key'].message_type = api_dot_pghr13__messages__pb2._VERIFICATIONKEYPGHR13
_VERIFICATIONKEY.fields_by_name['groth16_verification_key'].message_type = api_dot_groth16__messages__pb2._VERIFICATIONKEYGROTH16
_VERIFICATIONKEY.oneofs_by_name['VK'].fields.append(
  _VERIFICATIONKEY.fields_by_name['pghr13_verification_key'])
_VERIFICATIONKEY.fields_by_name['pghr13_verification_key'].containing_oneof = _VERIFICATIONKEY.oneofs_by_name['VK']
_VERIFICATIONKEY.oneofs_by_name['VK'].fields.append(
  _VERIFICATIONKEY.fields_by_name['groth16_verification_key'])
_VERIFICATIONKEY.fields_by_name['groth16_verification_key'].containing_oneof = _VERIFICATIONKEY.oneofs_by_name['VK']
_EXTENDEDPROOF.fields_by_name['pghr13_extended_proof'].message_type = api_dot_pghr13__messages__pb2._EXTENDEDPROOFPGHR13
_EXTENDEDPROOF.fields_by_name['groth16_extended_proof'].message_type = api_dot_groth16__messages__pb2._EXTENDEDPROOFGROTH16
_EXTENDEDPROOF.oneofs_by_name['EP'].fields.append(
  _EXTENDEDPROOF.fields_by_name['pghr13_extended_proof'])
_EXTENDEDPROOF.fields_by_name['pghr13_extended_proof'].containing_oneof = _EXTENDEDPROOF.oneofs_by_name['EP']
_EXTENDEDPROOF.oneofs_by_name['EP'].fields.append(
  _EXTENDEDPROOF.fields_by_name['groth16_extended_proof'])
_EXTENDEDPROOF.fields_by_name['groth16_extended_proof'].containing_oneof = _EXTENDEDPROOF.oneofs_by_name['EP']
DESCRIPTOR.message_types_by_name['VerificationKey'] = _VERIFICATIONKEY
DESCRIPTOR.message_types_by_name['ExtendedProof'] = _EXTENDEDPROOF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VerificationKey = _reflection.GeneratedProtocolMessageType('VerificationKey', (_message.Message,), {
  'DESCRIPTOR' : _VERIFICATIONKEY,
  '__module__' : 'api.snark_messages_pb2'
  # @@protoc_insertion_point(class_scope:zeth_proto.VerificationKey)
  })
_sym_db.RegisterMessage(VerificationKey)

ExtendedProof = _reflection.GeneratedProtocolMessageType('ExtendedProof', (_message.Message,), {
  'DESCRIPTOR' : _EXTENDEDPROOF,
  '__module__' : 'api.snark_messages_pb2'
  # @@protoc_insertion_point(class_scope:zeth_proto.ExtendedProof)
  })
_sym_db.RegisterMessage(ExtendedProof)


# @@protoc_insertion_point(module_scope)
