# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from api.groth16_messages_pb2 import (
    ExtendedProofGROTH16 as api___groth16_messages_pb2___ExtendedProofGROTH16,
    VerificationKeyGROTH16 as api___groth16_messages_pb2___VerificationKeyGROTH16,
)

from api.pghr13_messages_pb2 import (
    ExtendedProofPGHR13 as api___pghr13_messages_pb2___ExtendedProofPGHR13,
    VerificationKeyPGHR13 as api___pghr13_messages_pb2___VerificationKeyPGHR13,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class VerificationKey(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def pghr13_verification_key(self) -> api___pghr13_messages_pb2___VerificationKeyPGHR13: ...

    @property
    def groth16_verification_key(self) -> api___groth16_messages_pb2___VerificationKeyGROTH16: ...

    def __init__(self,
        *,
        pghr13_verification_key : typing___Optional[api___pghr13_messages_pb2___VerificationKeyPGHR13] = None,
        groth16_verification_key : typing___Optional[api___groth16_messages_pb2___VerificationKeyGROTH16] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> VerificationKey: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"VK",u"groth16_verification_key",u"pghr13_verification_key"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"VK",u"groth16_verification_key",u"pghr13_verification_key"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"VK",b"VK",u"groth16_verification_key",b"groth16_verification_key",u"pghr13_verification_key",b"pghr13_verification_key"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"VK",b"VK",u"groth16_verification_key",b"groth16_verification_key",u"pghr13_verification_key",b"pghr13_verification_key"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"VK",b"VK"]) -> typing_extensions___Literal["pghr13_verification_key","groth16_verification_key"]: ...

class ExtendedProof(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def pghr13_extended_proof(self) -> api___pghr13_messages_pb2___ExtendedProofPGHR13: ...

    @property
    def groth16_extended_proof(self) -> api___groth16_messages_pb2___ExtendedProofGROTH16: ...

    def __init__(self,
        *,
        pghr13_extended_proof : typing___Optional[api___pghr13_messages_pb2___ExtendedProofPGHR13] = None,
        groth16_extended_proof : typing___Optional[api___groth16_messages_pb2___ExtendedProofGROTH16] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> ExtendedProof: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"EP",u"groth16_extended_proof",u"pghr13_extended_proof"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"EP",u"groth16_extended_proof",u"pghr13_extended_proof"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"EP",b"EP",u"groth16_extended_proof",b"groth16_extended_proof",u"pghr13_extended_proof",b"pghr13_extended_proof"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"EP",b"EP",u"groth16_extended_proof",b"groth16_extended_proof",u"pghr13_extended_proof",b"pghr13_extended_proof"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"EP",b"EP"]) -> typing_extensions___Literal["pghr13_extended_proof","groth16_extended_proof"]: ...
