# Generated by Django 3.0.8 on 2020-08-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='merkletree',
            fields=[
                ('mid', models.AutoField(db_column='MID', max_length=11, primary_key=True, serialize=False)),
                ('tree_data', models.TextField(db_column='tree_data', max_length=40000)),
                ('is_new', models.BooleanField(db_column='is_new', default=False)),
            ],
            options={
                'db_table': 'merkletree',
            },
        ),
    ]
