# Generated by Django 3.0.8 on 2020-08-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zkclientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merkletree',
            name='blockNumber',
            field=models.IntegerField(db_column='blockNumber', default=1),
        ),
    ]
