# Generated by Django 3.0.8 on 2020-08-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zkclientapp', '0002_merkletree_blocknumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merkletree',
            name='is_new',
        ),
        migrations.AlterField(
            model_name='merkletree',
            name='mid',
            field=models.AutoField(db_column='MID', primary_key=True, serialize=False),
        ),
    ]
