# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/groth16_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api import ec_group_messages_pb2 as api_dot_ec__group__messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/groth16_messages.proto',
  package='zeth_proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x61pi/groth16_messages.proto\x12\nzeth_proto\x1a\x1b\x61pi/ec_group_messages.proto\"\xcf\x01\n\x16VerificationKeyGROTH16\x12\x36\n\x08\x61lpha_g1\x18\x01 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup1Affine\x12\x35\n\x07\x62\x65ta_g2\x18\x02 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup2Affine\x12\x36\n\x08\x64\x65lta_g2\x18\x04 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup2Affine\x12\x0e\n\x06\x61\x62\x63_g1\x18\x05 \x01(\t\"\xb9\x01\n\x14\x45xtendedProofGROTH16\x12/\n\x01\x61\x18\x01 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup1Affine\x12/\n\x01\x62\x18\x02 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup2Affine\x12/\n\x01\x63\x18\x03 \x01(\x0b\x32$.zeth_proto.HexPointBaseGroup1Affine\x12\x0e\n\x06inputs\x18\x04 \x01(\tb\x06proto3')
  ,
  dependencies=[api_dot_ec__group__messages__pb2.DESCRIPTOR,])




_VERIFICATIONKEYGROTH16 = _descriptor.Descriptor(
  name='VerificationKeyGROTH16',
  full_name='zeth_proto.VerificationKeyGROTH16',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alpha_g1', full_name='zeth_proto.VerificationKeyGROTH16.alpha_g1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='beta_g2', full_name='zeth_proto.VerificationKeyGROTH16.beta_g2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delta_g2', full_name='zeth_proto.VerificationKeyGROTH16.delta_g2', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='abc_g1', full_name='zeth_proto.VerificationKeyGROTH16.abc_g1', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=279,
)


_EXTENDEDPROOFGROTH16 = _descriptor.Descriptor(
  name='ExtendedProofGROTH16',
  full_name='zeth_proto.ExtendedProofGROTH16',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='zeth_proto.ExtendedProofGROTH16.a', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='zeth_proto.ExtendedProofGROTH16.b', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c', full_name='zeth_proto.ExtendedProofGROTH16.c', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='zeth_proto.ExtendedProofGROTH16.inputs', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=467,
)

_VERIFICATIONKEYGROTH16.fields_by_name['alpha_g1'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP1AFFINE
_VERIFICATIONKEYGROTH16.fields_by_name['beta_g2'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP2AFFINE
_VERIFICATIONKEYGROTH16.fields_by_name['delta_g2'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP2AFFINE
_EXTENDEDPROOFGROTH16.fields_by_name['a'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP1AFFINE
_EXTENDEDPROOFGROTH16.fields_by_name['b'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP2AFFINE
_EXTENDEDPROOFGROTH16.fields_by_name['c'].message_type = api_dot_ec__group__messages__pb2._HEXPOINTBASEGROUP1AFFINE
DESCRIPTOR.message_types_by_name['VerificationKeyGROTH16'] = _VERIFICATIONKEYGROTH16
DESCRIPTOR.message_types_by_name['ExtendedProofGROTH16'] = _EXTENDEDPROOFGROTH16
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VerificationKeyGROTH16 = _reflection.GeneratedProtocolMessageType('VerificationKeyGROTH16', (_message.Message,), {
  'DESCRIPTOR' : _VERIFICATIONKEYGROTH16,
  '__module__' : 'api.groth16_messages_pb2'
  # @@protoc_insertion_point(class_scope:zeth_proto.VerificationKeyGROTH16)
  })
_sym_db.RegisterMessage(VerificationKeyGROTH16)

ExtendedProofGROTH16 = _reflection.GeneratedProtocolMessageType('ExtendedProofGROTH16', (_message.Message,), {
  'DESCRIPTOR' : _EXTENDEDPROOFGROTH16,
  '__module__' : 'api.groth16_messages_pb2'
  # @@protoc_insertion_point(class_scope:zeth_proto.ExtendedProofGROTH16)
  })
_sym_db.RegisterMessage(ExtendedProofGROTH16)


# @@protoc_insertion_point(module_scope)
