# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from api.ec_group_messages_pb2 import (
    HexPointBaseGroup1Affine as api___ec_group_messages_pb2___HexPointBaseGroup1Affine,
    HexPointBaseGroup2Affine as api___ec_group_messages_pb2___HexPointBaseGroup2Affine,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class VerificationKeyPGHR13(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    ic = ... # type: typing___Text

    @property
    def a(self) -> api___ec_group_messages_pb2___HexPointBaseGroup2Affine: ...

    @property
    def b(self) -> api___ec_group_messages_pb2___HexPointBaseGroup1Affine: ...

    @property
    def c(self) -> api___ec_group_messages_pb2___HexPointBaseGroup2Affine: ...

    @property
    def gamma(self) -> api___ec_group_messages_pb2___HexPointBaseGroup2Affine: ...

    @property
    def gamma_beta_g1(self) -> api___ec_group_messages_pb2___HexPointBaseGroup1Affine: ...

    @property
    def gamma_beta_g2(self) -> api___ec_group_messages_pb2___HexPointBaseGroup2Affine: ...

    @property
    def z(self) -> api___ec_group_messages_pb2___HexPointBaseGroup2Affine: ...

    def __init__(self,
        *,
        a : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup2Affine] = None,
        b : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup1Affine] = None,
        c : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup2Affine] = None,
        gamma : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup2Affine] = None,
        gamma_beta_g1 : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup1Affine] = None,
        gamma_beta_g2 : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup2Affine] = None,
        z : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup2Affine] = None,
        ic : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> VerificationKeyPGHR13: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"a",u"b",u"c",u"gamma",u"gamma_beta_g1",u"gamma_beta_g2",u"z"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"a",u"b",u"c",u"gamma",u"gamma_beta_g1",u"gamma_beta_g2",u"ic",u"z"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"a",b"a",u"b",b"b",u"c",b"c",u"gamma",b"gamma",u"gamma_beta_g1",b"gamma_beta_g1",u"gamma_beta_g2",b"gamma_beta_g2",u"z",b"z"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"a",b"a",u"b",b"b",u"c",b"c",u"gamma",b"gamma",u"gamma_beta_g1",b"gamma_beta_g1",u"gamma_beta_g2",b"gamma_beta_g2",u"ic",b"ic",u"z",b"z"]) -> None: ...

class ExtendedProofPGHR13(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    inputs = ... # type: typing___Text

    @property
    def a(self) -> api___ec_group_messages_pb2___HexPointBaseGroup1Affine: ...

    @property
    def a_p(self) -> api___ec_group_messages_pb2___HexPointBaseGroup1Affine: ...

    @property
    def b(self) -> api___ec_group_messages_pb2___HexPointBaseGroup2Affine: ...

    @property
    def b_p(self) -> api___ec_group_messages_pb2___HexPointBaseGroup1Affine: ...

    @property
    def c(self) -> api___ec_group_messages_pb2___HexPointBaseGroup1Affine: ...

    @property
    def c_p(self) -> api___ec_group_messages_pb2___HexPointBaseGroup1Affine: ...

    @property
    def h(self) -> api___ec_group_messages_pb2___HexPointBaseGroup1Affine: ...

    @property
    def k(self) -> api___ec_group_messages_pb2___HexPointBaseGroup1Affine: ...

    def __init__(self,
        *,
        a : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup1Affine] = None,
        a_p : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup1Affine] = None,
        b : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup2Affine] = None,
        b_p : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup1Affine] = None,
        c : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup1Affine] = None,
        c_p : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup1Affine] = None,
        h : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup1Affine] = None,
        k : typing___Optional[api___ec_group_messages_pb2___HexPointBaseGroup1Affine] = None,
        inputs : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> ExtendedProofPGHR13: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"a",u"a_p",u"b",u"b_p",u"c",u"c_p",u"h",u"k"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"a",u"a_p",u"b",u"b_p",u"c",u"c_p",u"h",u"inputs",u"k"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"a",b"a",u"a_p",b"a_p",u"b",b"b",u"b_p",b"b_p",u"c",b"c",u"c_p",b"c_p",u"h",b"h",u"k",b"k"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"a",b"a",u"a_p",b"a_p",u"b",b"b",u"b_p",b"b_p",u"c",b"c",u"c_p",b"c_p",u"h",b"h",u"inputs",b"inputs",u"k",b"k"]) -> None: ...
